vim.opt.autoindent = true
vim.opt.background = "dark"
vim.opt.backspace = { "indent", "eol", "start" }
vim.opt.backup = false
vim.opt.backupcopy = "yes"
vim.opt.cmdheight = 2
vim.opt.compatible = false
vim.opt.completeopt = { "menuone", "noselect", "noinsert" }
vim.opt.conceallevel = 0
vim.opt.cursorline = true
vim.opt.expandtab = false
vim.opt.foldenable = false
vim.opt.hidden = true
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.incsearch = true
vim.opt.laststatus = 3
vim.opt.lcs = "tab:> ,eol:⏎,leadmultispace:· ,nbsp:·"
vim.opt.linebreak = true
vim.opt.list = true
vim.opt.mouse = ""
vim.opt.mousemodel = "extend"
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.ruler = true
vim.opt.scrolloff = 4
vim.opt.shiftwidth = 2
vim.opt.shortmess = vim.opt.shortmess:append({ c = true })
vim.opt.showbreak = "+++"
vim.opt.showmatch = true
vim.opt.showmode = false
vim.opt.showtabline = 2
vim.opt.signcolumn = "yes"
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.smarttab = true
vim.opt.softtabstop = 0
vim.opt.statusline = "%-10.10(%#StatusLineBold#%{mode()}%#StatusLine# %m%) %= %#StatusLineBold# %0.80f %#StatusLine# %= %10.10(%H%W%R%)"
vim.opt.swapfile = false
vim.opt.tabstop = 2
vim.opt.termguicolors = true
vim.opt.textwidth = 100
vim.opt.timeoutlen = 1000
vim.opt.undodir = vim.fn.expand("~/.config/nvim/undo")
vim.opt.undofile = true
vim.opt.undolevels = 100
vim.opt.updatetime = 200
vim.opt.wrap = false
vim.opt.writebackup = false
