git:
  autoFetch: false
  autoRefresh: false
  overrideGpg: true
  parseEmoji: true
  branchLogCmd: 'git log --graph --color=always --decorate --oneline {{branchName}} --'
  allBranchesLogCmd: 'git log --graph --all --color=always --decorate --oneline'
keybinding:
  universal:
    prevBlock-alt: 'h'
    nextBlock-alt: 'l'
    prevTab: 'H'
    nextTab: 'L'
    scrollLeft: <disabled>
    scrollRight: <disabled>
gui:
  language: 'en'
  scrollPastBottom: true
  showRandomTip: false
  showIcons: true
  theme:
    lightTheme: false
    activeBorderColor:
      - '#ffffff'
      - 'bold'
    inactiveBorderColor:
      - '#b0b0b0'
    searchingActiveBorderColor:
      - '#383838' 
      - 'bold'
    optionsTextColor: 
      - '#e0e0e0'
    selectedLineBgColor: 
      - '#4a4a4a'
    cherryPickedCommitBgColor:
      - '#383838'
    cherryPickedCommitFgColor:
      - '#4a4a4a'
    unstagedChangesColor:
      - '#e6c300'
    defaultFgColor:
      - '#d0d0d0'
os:
  edit: 'nvr --remote {{filename}}'
  editAtLine: 'nvr --remote +{{line}} {{filename}}'
reporting: 'off'
update:
  method: never
