git:
  autoFetch: false
  autoRefresh: false
  overrideGpg: true
  parseEmoji: true
customCommands:
  - command: 'git push --force-with-lease'
    context: 'global'
    description: 'force push with lease'
    key: '<c-f>'
    loadingText: 'Force pushing with lease to repository...'
    stream: yes
  - command: 'git push --tags'
    context: 'global'
    description: 'push all tags'
    key: '<c-t>'
    loadingText: 'Pushing tags to repository...'
    stream: yes
  - command: 'git pull --rebase'
    context: 'global'
    description: 'pull & rebase'
    key: '<c-p>'
    loadingText: 'Pulling and rebasing...'
    stream: yes
keybinding:
  universal:
    prevBlock-alt: 'h'
    nextBlock-alt: 'l'
    prevTab: 'H'
    nextTab: 'L'
    scrollLeft: null
    scrollRight: null
gui:
  language: 'en'
  scrollPastBottom: true
  showRandomTip: false
  showIcons: true
  theme:
    lightTheme: false
    activeBorderColor:
      - "#a6d189" # Green
      - bold
    inactiveBorderColor:
      - "#c6d0f5" # Text
    optionsTextColor:
      - "#8caaee" # Blue
    selectedLineBgColor:
      - "#414559" # Surface0
    selectedRangeBgColor:
      - "#414559" # Surface0
    cherryPickedCommitBgColor:
      - "#81c8be" # Teal
    cherryPickedCommitFgColor:
      - "#8caaee" # Blue
    unstagedChangesColor:
      - red       # Red
os:
  edit: 'nvr --remote {{filename}}'
  editAtLine: 'nvr --remote +{{line}} {{filename}}'
reporting: 'off'
update:
  method: never
