git:
  autoFetch: false
  autoRefresh: false
  overrideGpg: true
  parseEmoji: true
  branchLogCmd: 'git log --graph --color=always --decorate --oneline {{branchName}} --'
  allBranchesLogCmd: 'git log --graph --all --color=always --decorate --oneline'
keybinding:
  universal:
    prevBlock-alt: 'h'
    nextBlock-alt: 'l'
    prevTab: 'H'
    nextTab: 'L'
    scrollLeft: <disabled>
    scrollRight: <disabled>
gui:
  language: 'en'
  scrollPastBottom: true
  showRandomTip: false
  showIcons: true
  theme:
    lightTheme: false
    activeBorderColor:
      - "#a6d189" # Green
      - bold
    inactiveBorderColor:
      - "#c6d0f5" # Text
    optionsTextColor:
      - "#8caaee" # Blue
    selectedLineBgColor:
      - "#414559" # Surface0
    selectedRangeBgColor:
      - "#414559" # Surface0
    cherryPickedCommitBgColor:
      - "#81c8be" # Teal
    cherryPickedCommitFgColor:
      - "#8caaee" # Blue
    unstagedChangesColor:
      - red       # Red
os:
  edit: 'nvr --remote {{filename}}'
  editAtLine: 'nvr --remote +{{line}} {{filename}}'
reporting: 'off'
update:
  method: never
